name: Nightly test at main branch

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * 1-5'

jobs:
  setup:
    name: Setup variables
    runs-on: 'ubuntu-22.04'
    outputs:
      min_python: ${{ steps.vars.outputs.min_python }}
    steps:
      - uses: actions/checkout@v4
      - name: Get Python version for other CI jobs
        id: vars
        run: echo "min_python=$(cat .github/workflows/python-version-ci)" >> $GITHUB_OUTPUT

  tests:
    name: Tests
    needs: setup
    env:
        # Security note! The secrets are only added to workflows that run on trusted branches (main). If secrets are accessible in workflows that run on untrusted branches they can be extracted, see https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#exfiltrating-data-from-a-runner.
        ESS_PROTECTED_FILESTORE_USERNAME: ${{ secrets.ESS_PROTECTED_FILESTORE_USERNAME }}
        ESS_PROTECTED_FILESTORE_PASSWORD: ${{ secrets.ESS_PROTECTED_FILESTORE_PASSWORD }}
    strategy:
      matrix:
        os: ['ubuntu-22.04']
        python:
          - version: '${{needs.setup.outputs.min_python}}'
            tox-env: 'nightly'
    uses: ./.github/workflows/test.yml
    with:
      os-variant: ${{ matrix.os }}
      python-version: ${{ matrix.python.version }}
      tox-env: ${{ matrix.python.tox-env }}
